### ISSUE TITLE
鯖OSのupgrade

### ISSUE THREAD

**Issue by murachi** [murachi/nop#7]
16.04 はサポート切れてるのでアップグレードする必要がががが

[この辺](https://hachiilcane.hatenablog.com/entry/2020/05/02/231729)が参考になりそう。

**Comment by murachi** [comment]
MariaDB の 16.04 向け 10.04 リポジトリがサポート切れになったからか update で失敗するようになってしまい、色々やってたら削除してしまった末にインストールできなくなっちゃったので、あえなく OS アップグレード中。
とりあえず 18.04 にはなりました。
さくらのセットアップ情報は[こっちに移動していた模様](https://manual.sakura.ad.jp/vps/os-packages/ubuntu18.html)…。

**Comment by murachi** [comment]
色々とひどいことになってしまった…。
- 軽い気持ちで MariaDB 10.6 をインストールしたところ、 Trac が動かなくなってしまった。どうやら charset が utf8 -> utf8mb3 の読み替えが利かないらしくエラーになってしまう (utf8mb4 なら問題ない模様)。
- そこで、軽い気持ちでダウングレードしようと思い、 MariaDB 10.6 をアンインストールしてリポジトリを差し替え、 10.4 をインストールし直したところ、データが綺麗サッパリなくなってしまっていた。 10.6 アンインストール時にテーブルデータは消さないオプションを選んだはずなのに！！！
- あとになってMariaDBはダウングレードをサポートしていないらしいことに気がつく。やるにしても通常はSQLにダンプしてからやるものらしい。知らなかった…orz
- そこで仕方無しに再び 10.6 に差し戻したは良いが、残していたはずのテーブルデータファイルをそのまま持ってきてもデータベースが認識されない。
- そもそも InnoDB のテーブルファイルは表領域の番号とやらが一致しないと認識されないとかそういう仕様になっているらしく、なんだか[この辺に書かれたやり方](https://qiita.com/___uhu/items/74168be48c05638c7ac5)でもってテーブル1個1個復元していかないといけないらしい。つらい…(´・_・`)
  - それでもこの記事の人は番号が一致するまでやり直せという手順を「表領域を消す」という荒業で省力化することに気づいただけ凄いと思う。有り難し…
- 幸い `mailusers` は MyISAM だったらしくファイルコピーだけで復元できたものの、なぜか dovecot はまともに動いてくれていない。もうおぢさんくぢけそうだよ…(´；ω；｀)

**Comment by murachi** [comment]
メールは復活した。 `dovecot-mysql` が何故か入ってないことになってた(´・_・`)。とりあえず良かった…

**Comment by murachi** [comment]
残作業:
- 少なくとも以下の DB はデータを復活させる:
  - `trac-ideanote`
  - `harapeko_press`
  - `tmpbox`
- Trac のデータについて、 utf8 で保存されているデータをなんとか utf8mb4 に変換できないか検証する。 (mysqldump してから ddl 弄って投入しなおせばイケそうな気もするが…)

**Comment by murachi** [comment]
ブログも MyISAM だったのですぐ復旧できました。

tmpbox はこの際データリセットしても全く痛くないのでどうでもいいとして…

trac 系の InnoDB のやつですが、 `*.frm` ファイルは実際 cat したぐらいでは DDL は見れない模様。めっちゃバイナリファイルだった。

明日以降に[この辺](https://medium.com/@badalnaik/mariadb-mysql-restore-database-from-frm-and-ibd-files-6ea95269fba2)を試してみる。

**Comment by murachi** [comment]
[Twitter で助けを請うてみたり](https://twitter.com/T_MURACHI/status/1448414312188444674)もしてますが、望み薄ですな…(´・_・`)

そんなわけで、最後の手段に出ます。
1. trac_ideanote のリポジトリディレクトリのバックアップを取っておく。
2. trac_ideanote データベースを、 `character set utf8mb4 collate utf8mb4_bin` で新規作成。
3. trac_ideanote リポジトリを一旦まっさらにして `initenv` し、↑のDBにテーブルを吐き出させる。
4. この時点のデータベースの DDL をダンプする。
5. ダンプした DDL の `character set utf8mb4` を `utf8` に、 `collate utf8mb4_bin` を `utf8_bin` に書き換える。
   - **(10/18 追記)** 加えて、 `ENGINE=InnoDB` の後ろに、元々の trac_ideanote DB の row_format を再現すべく、 ~~`ROW_FORMAT=REDUNDANT`~~ `ROW_FORMAT=COMPACT` を書き加えてみた。
6. trac_ideanote データベースを drop し、↑のDDLを使って作り直す。
7. [これ](https://qiita.com/___uhu/items/74168be48c05638c7ac5)を試す。つまり、表領域を削除してから `*.frm`、 `*.ibd` ファイルの挿げ替えを行い、表領域の再読込を行う。
8. データに問題なくアクセスできるか確認し、問題なければ、 DDL、 DML 共に再びダンプする。
9. ダンプした DDL の `character set utf8` (`utf8mb3` かも) を `utf8mb4` に、 `collate utf8_bin` (`utf8mb3_bin` かも) を `utf8mb4_bin` に書き換える。
10. trac_ideanote データベースを再度 drop し、↑で修正したダンプを使って作り直す。
11. trac_ideanote のリポジトリディレクトリを、最初に取っておいていたバックアップにすげ替える。
12. サイトアクセス確認…

今の所、上記手順の 3 まで実施済み。

**Comment by murachi** [comment]
7 を試したらエラーになった。
```prompt
MariaDB [trac_ideanote]> alter table attachment import tablespace;
ERROR 1808 (HY000): Schema mismatch (Expected FSP_SPACE_FLAGS=0x15, .ibd file contains 0x0.)
```

[この辺の記事](https://next49.hatenadiary.jp/entry/20191113/1573616792)によると、 `ROW_FORMAT` というのを合わせてあげないといけないらしい。これのデフォルトが MySQL (mariaDB) のバージョンで異なるらしく… trac_ideanote はだいぶ昔に作ったテーブルなので[この辺の記事](https://mariadb.com/kb/en/innodb-row-formats-overview/#row-formats)によれば `REDUNDANT` にすべきらしい (10.6 のデフォルトは `dynamic`)。

5 と 6 の間に手順の追加が必要やな(´・_・`)

**Comment by murachi** [comment]
`ROW_FORMAT=REDUNDANT` を試してみたら、そもそもテーブル構築で行サイズ大きすぎるって怒られた(´・_・`)

```sh
murachi@ik1-314-17353:~/backup_trac$ mysql -u trac_master -p3Bd98Sbc9 trac_ideanote <ddl-trac_ideanote.sql 
ERROR 1118 (42000) at line 299: Row size too large (> 8123). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.
```

流石に `initenv` 時に同じエラーが出ていたとも思えないし、[ここの記事](https://mariadb.com/kb/en/innodb-row-formats-overview/#row-formats)読み返して見る限り、実は `ROW_FORMAT=COMPACT` が正解なんじゃないかって気がしてきた。

**Comment by murachi** [comment]
`ROW_FORMAT=COMPACT` でも `Row size too large` エラーは解消されず…(´・\_・\`) 何故だ…(´・_・`)

**Comment by murachi** [comment]
`ticket` テーブルだけ `ROW_FORMAT=DYNAMIC` でやってみた。
で、表領域の付替えを `attachment` テーブルと `ticket` テーブルだけ試してみたが、やはり表領域がないと怒られてしまう。

```sql
MariaDB [trac_ideanote]> alter table attachment discard tablespace;
Query OK, 0 rows affected (0.001 sec)

MariaDB [trac_ideanote]> alter table attachment import tablespace;
ERROR 1030 (HY000): Got error 194 "Tablespace is missing for a table" from storage engine InnoDB
MariaDB [trac_ideanote]> alter table ticket discard tablespace;
Query OK, 0 rows affected (0.003 sec)

MariaDB [trac_ideanote]> alter table ticket import tablespace;
ERROR 1030 (HY000): Got error 194 "Tablespace is missing for a table" from storage engine InnoDB
MariaDB [trac_ideanote]> 
```

**Comment by murachi** [comment]
表領域がないと怒られたのは `.ibd` ファイルの所有者が root になってるからだった。のでファイルの所有権を直してみたが、やはり Schema mismatch で怒られる。

```sql
MariaDB [trac_ideanote]> alter table ticket import tablespace;
ERROR 1808 (HY000): Schema mismatch (Expected FSP_SPACE_FLAGS=0x15, .ibd file contains 0x0.)
MariaDB [trac_ideanote]> alter table attachment import tablespace;
ERROR 1808 (HY000): Schema mismatch (Expected FSP_SPACE_FLAGS=0x15, .ibd file contains 0x0.)
MariaDB [trac_ideanote]> 
```

単に `COMPACT` は外れなだけなのか、これだけ合わせても駄目ということなのか…。

**Comment by murachi** [comment]
`REDUNDANT` も試したけどやっぱり駄目だった orz

**Comment by murachi** [comment]
mysqlfrm に立ち戻ってみたが… `utf8mb3` はサポートしてないとか意味不明なエラー吐かれた(´・_・`)

```
root@ik1-314-17353:/var/lib/mysql-10.6/trac_ideanote# mysqlfrm --server=trac_master:パスワード@localhost --port 33070 --user mysql ./ticket.frm
WARNING: Using a password on the command line interface can be insecure.
# Source on localhost: ... 
Traceback (most recent call last):
  File "/usr/bin/mysqlfrm", line 345, in <module>
    servers = connect_servers(source_values, None, conn_options)
  File "/usr/lib/python2.7/dist-packages/mysql/utilities/common/server.py", line 487, in connect_servers
    source = get_server(src_name, src_dict, quiet, verbose=verbose)
  File "/usr/lib/python2.7/dist-packages/mysql/utilities/common/server.py", line 334, in get_server
    server_conn.connect()
  File "/usr/lib/python2.7/dist-packages/mysql/utilities/common/server.py", line 1065, in connect
    self.db_conn.set_charset_collation(charset=res[0][1])
  File "/usr/lib/python2.7/dist-packages/mysql/connector/abstracts.py", line 648, in set_charset_collation
    CharacterSet.get_charset_info(charset, collation)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/constants.py", line 658, in get_charset_info
    info = cls.get_default_collation(charset)
  File "/usr/lib/python2.7/dist-packages/mysql/connector/constants.py", line 630, in get_default_collation
    raise ProgrammingError("Character set '%s' unsupported." % (charset))
mysql.connector.errors.ProgrammingError: Character set 'utf8mb3' unsupported.
root@ik1-314-17353:/var/lib/mysql-10.6/trac_ideanote# 
```

**Comment by murachi** [comment]
なんちゅーこった… `/etc/mysql/mariadb.conf.d/50-server.cnf` で `datadir` の向き先を変えただけであっさり DB が見えるようになった…

**Comment by murachi** [comment]
tmpbox は動いとるなぁ…。
てことはもしかしたら python2.7 の pymysql の問題?

**Comment by murachi** [comment]
もう一息っぽい。
uWSGI が Python2.7 のものなのか Python3.x のものなのかが問題なのかも。

**Comment by murachi** [comment]
uWSGI の何が問題なのかはまだよくわからんが、とりあえず unix socket を介さず HTTP を listen する ini ファイルを作って手動で uwsgi 起動したらちゃんと動いてくれた。

あと nginx で動かしてたときの uWSGI のログ出力を改めて確認したら 500 エラーを返してる。何らかアプリケーションは実行していて、どこかでコケてる…? 手動の場合と基本的な設定は変わらないはずなんだが…

**Comment by murachi** [comment]
普段使ってる ini ファイルを使って手動起動、 nginx も再起動して普通にアクセスできることを確認。

で、改めて `systemctl start trac.service` で起動してアクセスしたらやっぱり 502 Bad Gateway エラー。

そこでログを確認したらこんなの出てた。 `KeyboardInterrupt` ってどゆこと…??

```
*** Starting uWSGI 2.0.18 (64bit) on [Sat Nov  6 06:47:54 2021] ***
compiled with version: 5.4.0 20160609 on 25 October 2019 07:36:15
os: Linux-4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021
nodename: ik1-314-17353
machine: x86_64
clock source: unix
detected number of CPU cores: 3
current working directory: /var/Developer/trac/original
writing pidfile to /var/Developer/trac/run/uwsgi-original.pid
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
setgid() to 33
setuid() to 33
chdir() to /var/Developer/trac/original
your processes number limit is 7786
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /var/Developer/trac/run/uwsgi-original.sock fd 6
Python version: 2.7.17 (default, Feb 27 2021, 15:10:58)  [GCC 7.5.0]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 68, in <module>
    import os
  File "/usr/lib/python2.7/os.py", line 400, in <module>
    import UserDict
  File "/usr/lib/python2.7/UserDict.py", line 116, in <module>
    import _abcoll
  File "/usr/lib/python2.7/_abcoll.py", line 443, in <module>
    class KeysView(MappingView, Set):
  File "/usr/lib/python2.7/abc.py", line 87, in __new__
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
KeyboardInterrupt
```

**Comment by murachi** [comment]
KeyboardInterrupt の件は一旦忘れるとして、 `www-data` ユーザーさんに切り替えて手動実行したら 500 エラーになる状態が再現できた。 `www-data` ユーザーで実行できなくなっちゃってる原因が特定できれば多分解決。

**Comment by murachi** [comment]
とりあえず 500 エラーが出るのが `www-data` さんに `trac.ini` へのアクセス権がないことが原因であることが判明、無事にサービス起動で動くようになった…はずなんだが、サービス起動しようとすると謎の KeyboardInterrupt エラーで速攻止められちゃうという不安定な状況になってる。サーバー再起動すれば安定するようになるのかなぁ…(´・_・`)

**Comment by murachi** [comment]
サーバー再起動した。 Trac ちゃんと動いてる!!!
これで全ては解決です。良かった…｡･ﾟ･(ﾉД`)･ﾟ･｡
